---
- name: This playbook will install Docker
  hosts: all
  become: true   
  tasks
  - name:
    get_url: url=https://tomcat.apache.org/download-80.cgi dest=/home/ansible

  - name: Extract the file downloaded tomcat file
    command: tar xvf apache-tomcat-8.5.32.tar.gz

  - name: Move the Tomcat directory to a smaller one
    command: mv apache-tomcat-8.5.32 tomcat

  - name: Change Ownership and group of the Tomcat directory
    file: path=/home/ansible/tomcat owner=ansible group=ansible mode=775 state=directory recurse=yes

  - name: Start Tomcat                                                                                                          13,8          Top
    command: nohup /home/ansible/tomcat/bin/startup.sh # Execute command even after you have exited from the shell pro          14,2          33%
    become: true                                                                                                                15,8          66%
    become_user: ansible 