---
- name: Download JDK on all hosts
  hosts: all
  become: true
  
  vars:
    jdk_download_url: "https://download.java.net/openjdk/jdk16/ri/openjdk-16+36_linux-x64_bin.tar.gz"
    jdk_install_dir: "/usr/local/jdk"
  
  tasks:
    - name: Ensure JDK installation directory exists
      file:
        path: "{{ jdk_install_dir }}"
        state: directory
      
    - name: Download JDK archive
      get_url:
        url: "{{ jdk_download_url }}"
        dest: "/tmp/jdk.tar.gz"
      
    - name: Extract JDK archive
      unarchive:
        src: "/tmp/jdk.tar.gz"
        dest: "{{ jdk_install_dir }}"
        remote_src: true
        extra_opts: "--strip-components=1"
      
    - name: Set JDK environment variables
      lineinfile:
        dest: "/etc/environment"
        line: 'JAVA_HOME="{{ jdk_install_dir }}"'
      
    - name: Reload environment variables
      command: ". /etc/environment"
